# Generated by Django 3.1.2 on 2020-10-15 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('detail', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default='false')),
                ('acceptedBy', models.CharField(blank=True, default='', max_length=50)),
                ('answered', models.BooleanField(default='false')),
                ('expired', models.BooleanField(default='false')),
                ('quesImg', models.ImageField(blank=True, default='', null=True, upload_to='quesimages')),
                ('contextUrl', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ansImg', models.ImageField(blank=True, default='', null=True, upload_to='ansimages')),
                ('contextUrl', models.URLField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AskMe.question')),
            ],
        ),
    ]
