# Generated by Django 3.1.2 on 2020-10-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('quesNo', models.IntegerField(default=0)),
                ('ansNo', models.IntegerField(default=0)),
                ('profilepic', models.ImageField(blank=True, default='', null=True, upload_to='pictures')),
            ],
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='detail',
            new_name='ansText',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='detail',
            new_name='quesText',
        ),
    ]
