# Generated by Django 3.1.2 on 2020-10-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0002_auto_20201015_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
