# Generated by Django 3.1.2 on 2020-10-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0004_auto_20201016_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='quesText',
            field=models.CharField(default='', max_length=300),
        ),
    ]
