# Generated by Django 3.1.2 on 2020-10-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0006_auto_20201017_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default='', max_length=300),
        ),
    ]
