# Generated by Django 3.1.2 on 2020-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0007_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='workingOn',
            field=models.IntegerField(default=0),
        ),
    ]
