# Generated by Django 3.1.1 on 2020-10-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0007_question_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ansText',
            field=models.CharField(default='', max_length=300),
        ),
    ]
