# Generated by Django 3.1.2 on 2020-10-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0009_auto_20201021_2117'),
        ('AskMe', '0008_detail_workingon'),
    ]

    operations = [
    ]
