# Generated by Django 3.1.2 on 2020-10-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0010_merge_20201025_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='profilepic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media'),
        ),
    ]
