# Generated by Django 3.1.2 on 2020-10-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0011_auto_20201027_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='profilepic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pictures'),
        ),
    ]
