# Generated by Django 3.1.2 on 2020-10-29 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0013_anscomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('posted_by', models.CharField(default='', max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques_comment', to='AskMe.question')),
            ],
        ),
    ]
