# Generated by Django 3.1.2 on 2020-11-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AskMe', '0016_question_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='attachment',
            field=models.FileField(blank=True, default='', null=True, upload_to='ansfiles'),
        ),
        migrations.AddField(
            model_name='question',
            name='attachment',
            field=models.FileField(blank=True, default='', null=True, upload_to='quesfiles'),
        ),
    ]
